### ISSUE TITLE
installation error, sorry

### ISSUE THREAD

**Issue by zenrabbit** [RS-eco/rISIMIP#3]
Downloading GitHub repo RS-eco/rISIMIP@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/RS-eco/rISIMIP/tarball/HEAD' failed

**Comment by RS-eco** [comment]
Could you please provide an example of the code you use and maybe also your session info (by running sessionInfo() in R and copying the output here).

```{r}
remotes::install_github("RS-eco/rISIMIP", build_vignettes = TRUE)
```
and

```{r}
remotes::install_github("RS-eco/rISIMIP")
```
both work for me, but I am using a powerful Linux machine with an up-to-date R version.

**Comment by zenrabbit** [comment]
ok super thanks. I will try again on a different machine/instance.
best,
cj.
